TORCH_SPEED_VALUE = 0
SOLDER_SPEED_VALUE = 1

MENUAL_MODE = 0
AUTO_MODE = 1

GUN_VOLTAGE = 0
GUN_AMP = 1

SET_GUN_SPEED = 0
SET_SOLDER_SPEED = 1
AUTO_START = 8

MAX_TORCH_SPEED_MM_PER_MIN = 4000
MAX_SOLDER_SPEED_MM_PER_MIN = 1000
